import type { Product } from '@/types';

// Sample products for demonstration (will be replaced with Supabase data)
export const sampleProducts: Product[] = [
    {
        id: '1',
        title: 'Multicolor Flower Cushion',
        slug: 'multicolor-flower-cushion',
        description: 'A vibrant, hand-stitched floral cushion that brings a burst of color to any room. Crafted with 100% premium cotton, this cushion features intricate embroidery inspired by traditional Indian flora. The rich blend of oranges, purples, and greens creates a warm, inviting atmosphere perfect for living rooms and bedrooms.',
        base_price: 999,
        category: 'Cushion',
        has_variants: true,
        is_active: true,
        created_at: new Date().toISOString(),
        images: [
            { id: 'img1', product_id: '1', variant_id: null, image_url: 'https://images.unsplash.com/photo-1629949009765-40fc74c9ec21?w=800&q=80', display_order: 0 },
            { id: 'img2', product_id: '1', variant_id: null, image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80', display_order: 1 },
            { id: 'img3', product_id: '1', variant_id: null, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', display_order: 2 },
            { id: 'img4', product_id: '1', variant_id: null, image_url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80', display_order: 3 },
        ],
        variants: [
            { id: 'v1', parent_product_id: '1', variant_name: 'Red', sku: 'CUSH-FLR-RED', price: 999, stock_quantity: 12, created_at: new Date().toISOString() },
            { id: 'v2', parent_product_id: '1', variant_name: 'Blue', sku: 'CUSH-FLR-BLU', price: 1099, stock_quantity: 3, created_at: new Date().toISOString() },
            { id: 'v3', parent_product_id: '1', variant_name: 'Green', sku: 'CUSH-FLR-GRN', price: 999, stock_quantity: 8, created_at: new Date().toISOString() },
        ],
    },
    {
        id: '2',
        title: 'Bohemian Tasseled Cushion',
        slug: 'bohemian-tasseled-cushion',
        description: 'Embrace bohemian chic with this beautifully tasseled cushion cover. Handwoven with natural cotton fibers and adorned with playful tassels, it adds texture and bohemian flair to any seating arrangement. Perfect for creating that relaxed, eclectic look.',
        base_price: 799,
        category: 'Cushion',
        has_variants: true,
        is_active: true,
        created_at: new Date().toISOString(),
        images: [
            { id: 'img5', product_id: '2', variant_id: null, image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80', display_order: 0 },
            { id: 'img6', product_id: '2', variant_id: null, image_url: 'https://images.unsplash.com/photo-1629949009765-40fc74c9ec21?w=800&q=80', display_order: 1 },
        ],
        variants: [
            { id: 'v4', parent_product_id: '2', variant_name: 'Natural', sku: 'CUSH-BOH-NAT', price: 799, stock_quantity: 15, created_at: new Date().toISOString() },
            { id: 'v5', parent_product_id: '2', variant_name: 'Charcoal', sku: 'CUSH-BOH-CHA', price: 849, stock_quantity: 7, created_at: new Date().toISOString() },
        ],
    },
    {
        id: '3',
        title: 'Geometric Art Deco Cushion',
        slug: 'geometric-art-deco-cushion',
        description: 'A sophisticated cushion featuring bold geometric patterns inspired by Art Deco design. The striking gold and navy pattern commands attention while maintaining elegance. Made from high-quality, machine-washable cotton.',
        base_price: 1199,
        category: 'Cushion',
        has_variants: false,
        is_active: true,
        created_at: new Date().toISOString(),
        images: [
            { id: 'img7', product_id: '3', variant_id: null, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', display_order: 0 },
            { id: 'img8', product_id: '3', variant_id: null, image_url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80', display_order: 1 },
        ],
        variants: [],
    },
    {
        id: '4',
        title: 'Velvet Royal Cushion',
        slug: 'velvet-royal-cushion',
        description: 'Indulge in luxury with our velvet royal cushion. This opulent piece features sumptuous velvet fabric in rich, regal tones with delicate piped edges. The perfect accent for creating a sophisticated, luxurious ambiance.',
        base_price: 1499,
        category: 'Cushion',
        has_variants: true,
        is_active: true,
        created_at: new Date().toISOString(),
        images: [
            { id: 'img9', product_id: '4', variant_id: null, image_url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80', display_order: 0 },
            { id: 'img10', product_id: '4', variant_id: null, image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80', display_order: 1 },
        ],
        variants: [
            { id: 'v6', parent_product_id: '4', variant_name: 'Emerald', sku: 'CUSH-VLV-EMR', price: 1499, stock_quantity: 2, created_at: new Date().toISOString() },
            { id: 'v7', parent_product_id: '4', variant_name: 'Ruby', sku: 'CUSH-VLV-RBY', price: 1499, stock_quantity: 6, created_at: new Date().toISOString() },
            { id: 'v8', parent_product_id: '4', variant_name: 'Sapphire', sku: 'CUSH-VLV-SAP', price: 1599, stock_quantity: 0, created_at: new Date().toISOString() },
        ],
    },
    {
        id: '5',
        title: 'Minimalist Linen Cushion',
        slug: 'minimalist-linen-cushion',
        description: 'Simplicity at its finest. This minimalist linen cushion brings quiet sophistication to any space with its clean lines and natural texture. Perfect for modern, Scandinavian, and contemporary interiors.',
        base_price: 699,
        category: 'Cushion',
        has_variants: true,
        is_active: true,
        created_at: new Date().toISOString(),
        images: [
            { id: 'img11', product_id: '5', variant_id: null, image_url: 'https://images.unsplash.com/photo-1629949009765-40fc74c9ec21?w=800&q=80', display_order: 0 },
        ],
        variants: [
            { id: 'v9', parent_product_id: '5', variant_name: 'Oat', sku: 'CUSH-LIN-OAT', price: 699, stock_quantity: 20, created_at: new Date().toISOString() },
            { id: 'v10', parent_product_id: '5', variant_name: 'Sage', sku: 'CUSH-LIN-SAG', price: 699, stock_quantity: 18, created_at: new Date().toISOString() },
        ],
    },
    {
        id: '6',
        title: 'Tropical Palm Cushion',
        slug: 'tropical-palm-cushion',
        description: 'Bring the tropics home with our vibrant palm-print cushion. Featuring bold palm fronds in lush greens on a crisp white background, this cushion adds instant vacation vibes to any space.',
        base_price: 899,
        category: 'Cushion',
        has_variants: false,
        is_active: true,
        created_at: new Date().toISOString(),
        images: [
            { id: 'img12', product_id: '6', variant_id: null, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', display_order: 0 },
            { id: 'img13', product_id: '6', variant_id: null, image_url: 'https://images.unsplash.com/photo-1629949009765-40fc74c9ec21?w=800&q=80', display_order: 1 },
        ],
        variants: [],
    },
];
